- menu_name: "Services"

- name: "Contact"
  url: "<https://mailto:hpigot@protonmail.com"
  title: "Email Harry"

- name: "RSS"
  url: "/feed.xml"
  title: "Subscribe to RSS Feed"

- name: "Atom"
  url: "/atom.xml"
  title: "Subscribe to Atom Feed"

# - name: "sitemap.xml"
#   url: "/sitemap.xml"
#   title: "Sitemap for Google Webmaster Tools"
